version: "3.9"

services:
  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./data/var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: app
      MYSQL_PASSWORD: app2021
      MYSQL_DATABASE: catalogo
      MYSQL_ROOT_PASSWORD: titanic2200
  config-service:
    build: ./config-service
    image: config-service:latest
    ports:
      - "8888:8888"
    environment:
      CONFIG_GIT_URI: https://github.com/castrohectora/CursoMS/config-data
      CONFIG_GIT_LABEL: config-server
  eureka-service:
    build: ./eureka-service
    image: eureka-service:latest
    ports:
      - "8761:8761"
    depends_on:
      - "config-service"
    environment:
      DISCOVERY_HOST: eureka-service
      DISCOVERY_PORT: 8761
      CONFIG_HOST: config-service
      CONFIG_PORT: 8888
      WAIT_HOSTS: config-service:8888
  user-service:
    build: ./user-service
    image: user-service:latest
    ports:
      - "8081:8081"
    depends_on:
      - "database"
      - "config-service"
    environment:
      DB_SERVER: database
      DB_NAME: catalogo
      DB_USER: root
      DB_PASSWD: titanic2200
      DISCOVERY_HOST: eureka-service
      DISCOVERY_PORT: 8761
      CONFIG_HOST: config-service
      CONFIG_PORT: 8888
      WAIT_HOSTS: config-service:8888,database:3306,eureka-service:8761
  gateway:
    build: ./gateway-service
    image: gateway:latest
    ports:
      - "8080:8080"
    depends_on:
      - "config-service"
      - "eureka-service"
    environment:
      DISCOVERY_HOST: eureka-service
      DISCOVERY_PORT: 8761
      CONFIG_HOST: config-service
      CONFIG_PORT: 8888
      WAIT_HOSTS: config-service:8888,eureka-service:8761
