version: "3.9"

services:
  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./data/var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: app
      MYSQL_PASSWORD: app2021
      MYSQL_DATABASE: catalogo
      MYSQL_ROOT_PASSWORD: titanic2200
  configserver:
    build: ./config-service
    image: configserver:latest
    ports:
      - "8888:8888"
    environment:
      CONFIG_GIT_URI: https://github.com/castrohectora/CursoMS/config-data
      CONFIG_GIT_LABEL: config-server
  servicediscovery:
    build: ./eureka-service
    image: servicediscovery:latest
    ports:
      - "8761:8761"
    depends_on:
      - "configserver"
    environment:
      DISCOVERY_HOST: servicediscovery
      DISCOVERY_PORT: 8761
      CONFIG_HOST: configserver
      CONFIG_PORT: 8888
      WAIT_HOSTS: configserver:8888
  user-service:
    build: ./user-service
    image: user-service:latest
    ports:
      - "8081:8081"
    depends_on:
      - "database"
      - "configserver"
    environment:
      DB_SERVER: database
      DB_NAME: catalogo
      DB_USER: root
      DB_PASSWD: titanic2200
      DISCOVERY_HOST: servicediscovery
      DISCOVERY_PORT: 8761
      CONFIG_HOST: configserver
      CONFIG_PORT: 8888
      WAIT_HOSTS: configserver:8888, database:3306, servicediscovery:8761
  gateway:
    build: ./gateway-service
    image: gateway:latest
    ports:
      - "8080:8080"
    depends_on:
      - "configserver"
      - "servicediscovery"
    environment:
      DISCOVERY_HOST: servicediscovery
      DISCOVERY_PORT: 8761
      CONFIG_HOST: configserver
      CONFIG_PORT: 8888
      WAIT_HOSTS: configserver:8888, servicediscovery:8761
