version: "3.9"

services:
  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./data/var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: app
      MYSQL_PASSWORD: app2022
      MYSQL_DATABASE: ejemploMS
      MYSQL_ROOT_PASSWORD: passroot
  configservice:
    build: ./config-service
    image: configservice:latest
    ports:
      - "8888:8888"
    environment:
      CONFIG_GIT_URI: https://github.com/castrohectora/config-data
      CONFIG_GIT_LABEL: main
  eurekaservice:
    build: ./eureka-service
    image: eurekaservice:latest
    ports:
      - "8761:8761"
    depends_on:
      - "configservice"
    environment:
      DISCOVERY_HOST: eurekaservice
      DISCOVERY_PORT: 8761
      CONFIG_HOST: configservice
      CONFIG_PORT: 8888
      WAIT_HOSTS: configservice:8888
  user-service:
    build: ./user-service
    image: userservice:latest
    ports:
      - "8081:8081"
    depends_on:
      - "database"
      - "configservice"
    environment:
      DB_SERVER: database
      DB_NAME: ejemploMS
      DB_USER: app
      DB_PASSWD: app2022
      DISCOVERY_HOST: eurekaservice
      DISCOVERY_PORT: 8761
      CONFIG_HOST: configservice
      CONFIG_PORT: 8888
      WAIT_HOSTS: configservice:8888,database:3306,eurekaservice:8761
  bike-service:
    build: ./bike-service
    image: bikeservice:latest
    ports:
      - "8082:8082"
    depends_on:
      - "database"
      - "configservice"
    environment:
      DB_SERVER: database
      DB_NAME: ejemploMS
      DB_USER: app
      DB_PASSWD: app2022
      DISCOVERY_HOST: eurekaservice
      DISCOVERY_PORT: 8761
      CONFIG_HOST: configservice
      CONFIG_PORT: 8888
      WAIT_HOSTS: configservice:8888,database:3306,eurekaservice:8761
  car-service:
    build: ./car-service
    image: carservice:latest
    ports:
      - "8083:8083"
    depends_on:
      - "database"
      - "configservice"
    environment:
      DB_SERVER: database
      DB_NAME: ejemploMS
      DB_USER: app
      DB_PASSWD: app2022
      DISCOVERY_HOST: eurekaservice
      DISCOVERY_PORT: 8761
      CONFIG_HOST: configservice
      CONFIG_PORT: 8888
      WAIT_HOSTS: configservice:8888,database:3306,eurekaservice:8761
  gateway:
    build: ./gateway-service
    image: gateway:latest
    ports:
      - "8080:8080"
    depends_on:
      - "configservice"
      - "eurekaservice"
    environment:
      DISCOVERY_HOST: eurekaservice
      DISCOVERY_PORT: 8761
      CONFIG_HOST: configservice
      CONFIG_PORT: 8888
      WAIT_HOSTS: configservice:8888, eurekaservice:8761
