server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.instance_id:${random.value}}

resilience4j.circuitbreaker:
    instances:
        carsCB:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
        bikesCB:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
        allCB:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10

spring:
  application:
    zipkin: http://localhost:9411

  datasource:
    url: jdbc:mysql://localhost:3306/users?verifyServerCertificate?=false&useSLL=false&serverTimezone=UTC&useLegacyDateTimeCode=false

    #username and password de la base de datos
    username: root
    password: #90ch0la9ant3ra

  #Mostrar SQL queries que se realizan
  jpa:
    show-sql: true

    #Actualiza la base de datos y crea la entidad
    hibernate:
      ddl-auto: update

    #generate optimization hibernate SQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
