server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI:https://github.com/castrohectora/config-data}
          refreshRate: 30
          default-label: ${CONFIG_GIT_LABEL:main}
