server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          default-label: ${CONFIG_GIT_LABEL:config-server-docker}
          uri: ${CONFIG_GIT_URI:https://github.com/castrohectora/CursoMS}
          searchPaths: config-data
          refreshRate: 30
          username: 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
          password:
