server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          default-label: ${CONFIG_GIT_LABEL:main}
          uri: ${CONFIG_GIT_URI:https://github.com/castrohectora/CursoMS/tree/main/config-data}

          refreshRate: 30
