server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          skip-ssl-validation: true
          clone-on-start: true
          default-label: ${CONFIG_GIT_LABEL:config-server-docker}
          uri: ${CONFIG_GIT_URI:https://github.com/castrohectora/CursoMS}
          searchPaths: config-data
          refreshRate: 30
