server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: auth-server
          uri: https://github.com/castrohectora/CursoMS
          search-paths: config-data
  application:
    name: config-service

